import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import videosRouter from "./videos";
import jobsRouter from "./jobs";
import segmentsRouter from "./segments";
import exportsRouter from "./exports";
import statsRouter from "./stats";
import nleExportRouter from "./nle-export";
import stylesRouter from "./styles";
import authRouter from "./auth";
import googleDriveRouter from "./google-drive";
import youtubeRouter from "./youtube";
import trainingRouter from "./training";
import styleProfilesRouter from "./styleProfiles";
import musicRouter from "./music";
import markersRouter from "./markers";
import audioTracksRouter from "./audioTracks";
import commentsRouter from "./comments";
import checkpointsRouter from "./checkpoints";
import collaborationRouter from "./collaboration";
import edlRouter from "./edl";
import batchOpsRouter from "./batch-ops";
import aiIntelligenceRouter from "./ai-intelligence";
import audioToolsRouter from "./audio-tools";
import colorToolsRouter from "./color-tools";
import exportToolsRouter from "./export-tools";
import socialIntelligenceRouter from "./social-intelligence";
import socialUploadRouter from "./social-upload";
import thumbnailsRouter from "./thumbnails";
import workflowsRouter from "./workflows";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(projectsRouter);
router.use(videosRouter);
router.use(jobsRouter);
router.use(segmentsRouter);
router.use(exportsRouter);
router.use(statsRouter);
router.use(nleExportRouter);
router.use(stylesRouter);
router.use(googleDriveRouter);
router.use(youtubeRouter);
router.use(trainingRouter);
router.use(styleProfilesRouter);
router.use(musicRouter);
router.use(markersRouter);
router.use(audioTracksRouter);
router.use(commentsRouter);
router.use(checkpointsRouter);
router.use(collaborationRouter);
router.use(edlRouter);
router.use(batchOpsRouter);
router.use(aiIntelligenceRouter);
router.use(audioToolsRouter);
router.use(colorToolsRouter);
router.use(exportToolsRouter);
router.use(socialIntelligenceRouter);
router.use(socialUploadRouter);
router.use(thumbnailsRouter);
router.use(workflowsRouter);

export default router;
